### ISSUE TITLE
Ability to export multiple reports in one go

### ISSUE THREAD

**Issue by andyofsmeg** [pharmaR/risk_assessment#1]
Currently reports must be exported one at a time.  This might form part of a wider 'overview' dashboard showing the status of all packages in the DB.

**Comment by andyofsmeg** [comment]
Requires resolution of #2 before it can be implemented

**Comment by AARON-CLARK** [comment]
@andofsmeg & @marlycormar, how do you envision this being executed from the UI? I think download button makes the most sense on the "Upload Package" tab or since that is the only spot you can see all the packages that were uploaded in one place. Perhaps above the list of packages?

![image](https://user-images.githubusercontent.com/17878953/89541271-29a1ef00-d7cc-11ea-9da3-581519c1c0c5.png)

**Comment by AARON-CLARK** [comment]
Another question for @andyofsmeg & @marlycormar: upon clicking such a button, would the user get a zip file that includes all the reports? Or should the user receive one large html/ docx report with a table of contents to quickly jump to each package? Thanks!

**Comment by AARON-CLARK** [comment]
please see #10

**Comment by AARON-CLARK** [comment]
Another pertinent question about the design of the multi-report download feature:

https://github.com/pharmaR/risk_assessment/pull/10#issuecomment-671505926

**Comment by marlycormar** [comment]
Hi @AARON-CLARK, since we can potentially have lots of packages on the db, it may be feasible to create the 'overview' dashboard/tab that Andy suggested or any set space for showing the status of all the packages in the db. From there we could select multiple packages and generate reports. What do you think?

**Comment by marlycormar** [comment]
Reopening issue to evaluate the 'overview' dashboard Andy mentioned.

**Comment by marlycormar** [comment]
Closing this issue in favor of the more specialized one here https://github.com/pharmaR/risk_assessment/issues/51.
