### ISSUE TITLE
how to register users

### ISSUE THREAD

**Issue by dingying85** [pharmaR/risk_assessment#164]
Dear Developers,

I downloaded the app and trying to laugh on my desktop. However, it asks for userid and password. May I ask any tutorial to set that? Thanks.

**Comment by marlycormar** [comment]
Dear @dingying85, thanks for reaching out. We are currently working on improving the documentation and the app (look out for PR #162!). In the meantime, please follow the documentation [here](https://pharmar.github.io/risk_assessment/Managing_Userids_and_Passwords) to setup authentication. Let us know if something is not clear or missing; we will appreciate it!

**Comment by dingying85** [comment]
Thanks a lot. That is very helpful, I just tried package dplyr and the risk
score is 0.13. It would be great if we could also have some documentation
about the scale of the scores and what range is considered low risk. -Ying

Marly Gotti ***@***.***> 于2022年1月23日周日 20:05写道：

**Comment by marlycormar** [comment]
I am glad you were able to try the app!

There is some information on that regard on the **Assessment Criteria** (top right corner info icon) on the app. To give you an idea, the score ranges from 0 to 1, 0 being the _lowest possible risk_ a package can have.
Since assessing risk is subjective, the reviewer can analyze the metrics and score as a whole, and then can assign a low/medium/high risk to the package using the app based on different criteria (e.g., based on the package's intended use or based on his/her company's take on validation).

**Comment by marlycormar** [comment]
Hi @dingying85, I'll close this issue as it has been resolved. But if you have any questions, please feel free to reopen it or open a new issue.
