### ISSUE TITLE
Fix downloads plot on the community usage metrics tab

### ISSUE THREAD

**Issue by marlycormar** [pharmaR/risk_assessment#171]
- [x] Show month/year on the x-axis.
- [x] Use app font/color in the plot.
- [x] show data (that's currently missing) for today's month, last year
- [x] show current version release in plot

**Comment by Robert-Krajcik** [comment]
I am addressing some more issues as well.
For example, the one-year range slider shows 7 months
![image](https://user-images.githubusercontent.com/75215958/155192922-bd5a6796-83ad-466d-844b-a53e5a010fd7.png)
The six month range shows 1 month
![image](https://user-images.githubusercontent.com/75215958/155193035-540062ff-b4e6-4411-99f6-8a1f167eedd7.png)
and the last release is not showing anything
![image](https://user-images.githubusercontent.com/75215958/155193099-9b91446e-d50f-44d8-8fd5-ac8bfa22c12a.png)

**Comment by Robert-Krajcik** [comment]
before
![image](https://user-images.githubusercontent.com/75215958/155193321-8bef3702-7da7-4d09-818c-f1fb59ae593e.png)

after
![image](https://user-images.githubusercontent.com/75215958/155194227-41da357e-c8ec-45a0-900f-c889deef92bb.png)
I like seeing the versions next to the bars.

**Comment by Robert-Krajcik** [comment]
Now the one-year range slider shows 1 year, month over month:
![image](https://user-images.githubusercontent.com/75215958/155194780-1fba90dc-c405-4f0c-8c02-4a91743124e8.png)

and the six month goes back 7 months
![image](https://user-images.githubusercontent.com/75215958/155194920-750b0fe4-d81c-402d-8912-01d2d95fbe08.png)

and the last release looks correct
![image](https://user-images.githubusercontent.com/75215958/155195107-64a6b32d-e227-4246-81da-8dd33d3bf855.png)

**Comment by AARON-CLARK** [comment]
Found another issue with the plot: it's missing the data for today's month, last year (which was fixed with PR #165 but never merged). I will go through that old PR (intended for `master`) to see what else we are missing.

![image](https://user-images.githubusercontent.com/17878953/156784394-6dacf332-ed11-45f0-87cd-e12a11d3f6d4.png)

**Comment by AARON-CLARK** [comment]
Found another issue: since the code is only pulling from the [CRAN archive](https://cran.r-project.org/src/contrib/Archive/), it's not capturing the currently version release. For example, the image above shows `dplyr 1.0.7` was the last release, in June of 2021. But really, the lastest (and current) release is `dplyr 1.0.8` which was [released](https://github.com/tidyverse/dplyr/releases?page=1) in Feb 2022!
