### ISSUE TITLE
Considering deleting the loggit.json

### ISSUE THREAD

**Issue by marlycormar** [pharmaR/risk_assessment#18]
The loggit.json seems to store information about the app that should not be stored in the repo.

**Comment by Robert-Krajcik** [comment]
There's no mention of this in the User Documentation, and only one line in README.md
Line 19 in App.R has
```{R}
set_logfile("loggit.json")
```
function `loggit()` is used in `dbupload.R`, `sidebar.R` and `uploadpackage.R`

help details:

A suggested use of this function would be to call it early, to log to the current working directory, as follows: `set_logfile(paste0(getwd(), "/loggit.log"))`. If you are using loggit in your package, you can wrap this function in `.onLoad()` so that the logfile is set when your package loads.

Examples -- set to temporary directory

`set_logfile(file.path(tempdir(), "loggit.log"))`

**Comment by AARON-CLARK** [comment]
> The loggit.json seems to store information about the app that should not be stored in the repo.

Agreed. I removed this file in PR #10

**Comment by Robert-Krajcik** [comment]
@marlycormar asked me to just put it in the .gitignore file for now
