### ISSUE TITLE
Replace observe(s) with observeEvent(s) in sidebar.R

### ISSUE THREAD

**Issue by ghost** [pharmaR/risk_assessment#20]
observeEvent is more efficient

**Comment by marlycormar** [comment]
Hi @Robert-Krajcik, I think there is a lot of space for improvement in this direction, so this is a good issue. Since `observe` functions are used without care, we should change them cautiously since we know that `observe` functions can be correctly replaced by `observeEvents` if we specify the events correctly. Observers always work =)

**Comment by Robert-Krajcik** [comment]
You are right, @marlycormar  We first need to understand what is being observed.
