### ISSUE TITLE
Need to provide a quick configuration to accesss an external db

### ISSUE THREAD

**Issue by ghost** [pharmaR/risk_assessment#23]
Instead of us writing into our own "silos" we should think about connecting to at least a department-wide db

**Comment by marlycormar** [comment]
@Robert-Krajcik we discussed this last time. 

We decided to create a vignette to instruct the users how to connect to a remote mysql db. We also discussed changing the db to MySQL but decided not to do that since it will require the user to have MySQL installed. Staying then with SQLite & adding a vignette to guide the user to connect to a remote db. Anything missing @Robert-Krajcik?
