### ISSUE TITLE
How to convert SQLite to either MySQL or MariaDB

### ISSUE THREAD

**Issue by marlycormar** [pharmaR/risk_assessment#28]

**Comment by Robert-Krajcik** [comment]
I'll look into this and create a PR

**Comment by Robert-Krajcik** [comment]
First thing you need to do is download mysql-installer-web-community-8.0.21.0.msi
from https://dev.mysql.com/downloads/mysql/5.5.html?os=3&version=5
and then get someone from IT to "install" it (add their user name and admin password)

Then run the mysql command line client (supply the root password you created)
and create a local database.  I called it "mydatabase"
![image](https://user-images.githubusercontent.com/62262182/90553727-dda76080-e162-11ea-8802-d0e945ee01b2.png)

Next,
`install.packages("RMySQL")`
and add `RMySQL` to `setup.R`
and edit `utils.R` and replace all instances of `RSQLite::SQLite()`  with `RMySQL::MySQL()`

There is a bit more setup work
```{r}
db_name <- "mydatabase"
db_user <- Sys.getenv("USERNAME")
db_password <- "mysqlpassword"
db_host <- '127.0.0.1' # for local access
db_port <- 3306
```
the db_password is actually the one I set up for my userid.

in the create_db function we replace
`con <- dbConnect(RSQLite::SQLite() , db_name)`
with
```{r}
con <-  dbConnect(RMySQL::MySQL(), user = db_user, password = db_password,  
dbname = db_name, host = db_host, port = db_port)
```
This is just to run MySQL locally, you would set up your own passwords.
But if we had a shared DB somewhere we'd have to set up user accounts and passwords

Now that I got this figured out,
I just saw a note in one of the StackOverflow responses:

`The RMySQL package is not under active development anymore because RMariaDB is intended to be its replacement, this is from the official GitHub repository:
NOTE: this package is being phased out in favor of the new RMariaDB package.`

[I can't connect RStudio with MySQL](https://community.rstudio.com/t/i-cant-connect-rstudio-with-mysql/50224)

Comments? @marlycormar or @MayaGans and/or @AARON-CLARK

**Comment by marlycormar** [comment]
It would be a good idea to leave SQLite db by default but provide the user a 'quick' way to set up another db (maybe MariaDB since it is better supported).

**Comment by Robert-Krajcik** [comment]
Created a vignette and a PR for converting SQLite to MySQL.  
Will look into MariaDB as well today.

**Comment by Robert-Krajcik** [comment]
Have PRs #37 and #38 which create a vignettes folder and add the R Markdown files
