### ISSUE TITLE
Asynchronous assessment

### ISSUE THREAD

**Issue by marlycormar** [pharmaR/risk_assessment#5]
Make assessment asynchronous so that the user can see metrics on some of the packages while the rest loads.

**Comment by MayaGans** [comment]
I'm not sure about implementation but this may be helpful to explore: https://rstudio.github.io/promises/articles/futures.html

**Comment by AARON-CLARK** [comment]
Hi all, 

The talk delivered by Joe Cheng was from a conference I attended a few years back. I found his presentation on youtube [here](https://youtu.be/Wy3TY0gOmJw?t=1113). I took a screenshot of the list he was referring to and he only addressed those 3 (highlighted) tools in his talk. It should be noted his talk was centered on speeding shiny apps in production, so slow code... not necessarily the situation we are in. Regardless, Joe gave this warning: "Async is hard, that's why it's the last resort. But if you need it, you really need it and I encourage you to study [my documentation] carefully. Maya's link on Promises / Futures is the right place to start if we need it.

![image](https://user-images.githubusercontent.com/17878953/89227484-c3d71c80-d5ab-11ea-90b6-7bf59723e030.png)

**Comment by marlycormar** [comment]
Thanks @MayaGans and @AARON-CLARK. These tools are worth exploring.

**Comment by AARON-CLARK** [comment]
Haven't researched fully, by [shiny.worker](https://github.com/Appsilon/shiny.worker) package was just released on CRAN and is supposed to help move work to separate processors to get work done faster. Not sure if this package will be valuable for `risk_assessment` but it's worth looking into!

**Comment by marlycormar** [comment]
Will refer back to this issue in another one encompassing all potential new features.
